version: '3'
services:
  spigot:
    build: images/ubuntu
    environment:
    - REV=1.15.2
    - MOTD=MC006
    - POLL=true
    - EULA=TRUE
    - OPS=ponsfrilus,_T2006_
    - PVP=false
    - WORLDBORDER=true
    - DYNMAP=true
    - ESSENTIALS=false
    - PERMISSIONSEX=true
    - CLEARLAG=true
    - JVM_OPTS=-Xmx1792M -Xms1024M
    volumes:
    - ./data:/minecraft
    ports:
    - "25565:25565"
    - "8123:8123"
